[package]
name = "bevy_http_client"
description = "A simple HTTP client for Bevy"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/foxzool/bevy_http_client"
authors = ["FoxZoOL <zhooul@gmail.com>"]
license = "MIT OR Apache-2.0"
keywords = ["bevy", "http", "plugin"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.0", default-features = false }
ehttp = { version = "0.3.0", features = ["native-async"] }
futures-lite = "1.11.3"