[package]
name = "bevy_http_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.0", default-features = false }
ehttp = { version = "0.3.0", features = ["native-async"] }
futures-lite = "1.11.3"